package edu.udel.cis.vsl.civl.model.IF.expression;

/**
 * This class represents a set of MPI contract expressions:
 * <ol>
 * <li>\mpi_empty_in: expresses that a receiving buffer is empty.</li>
 * <li>\mpi_empty_out: expresses that a sending buffer is empty.</li>
 * <li>\mpi_agree: expresses that an variable is same at the beginning for all
 * processes.</li>
 * <li>\mpi_equals: expresses that two pointers are pointing to the equal
 * obejects.</li>
 * <li>\mpi_region: represents an memory object in an MPI program.</li>
 * </ol>
 * 
 * @author xxxx
 *
 */
public interface MPIContractExpression extends Expression {
	static public enum MPI_CONTRACT_EXPRESSION_KIND {
		/**
		 * The expression in CIVL model representing the \mpi_agree expression
		 * in ACSL annotations:
		 */
		MPI_AGREE,
		/**
		 * The expression in CIVL model representing the \mpi_buf expression in
		 * ACSL annotations:
		 */
		MPI_BUF,
		/**
		 * The expression in CIVL model representing the \mpi_extent expression
		 * in ACSL annotations:
		 */
		// MPI_EXTENT,
		/**
		 * The expression in CIVL model representing the \mpi_reduce expression
		 * in ACSL annotations:
		 */
		// MPI_NONOVERLAPPING, replaced with an abstract function
		MPI_REDUCE,
		/**
		 * Representing an \mpi_seq_t type object extracted from an \mpi_but_t
		 * object at a state. This expression is generated by CIVL model
		 * translator. It has no counter-part in the ACSL-MPI contract language.
		 */
		MPI_SEQ,
	}

	/**
	 * Returns MPI_CONTRACT_EXPRESSION_KIND which denotes the exact kind of a
	 * general MPI contract expression.
	 * 
	 * @return
	 */
	MPI_CONTRACT_EXPRESSION_KIND mpiContractKind();

	/**
	 * Returns an array of arguments of an MPI contract expression.
	 * 
	 * @return
	 */
	Expression[] arguments();
}
